name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install bundler
        run: |
          gem install bundler
          bundle install

      - name: Set up primary database
        env:
          POSTGRES_DB: rails_react_test
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/rails_react_test"
        run: bin/rails db:create:primary db:migrate:primary

      - name: Run tests
        env:
          PG_USER: postgres
          PG_PASSWORD: postgres
        run: |
          bundle exec rspec