name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install bundler
        run: |
          gem install bundler
          bundle install

      - name: Set up PostgreSQL
        uses: apocalyptech/postgres-setup-action@v2
        with:
          postgres-version: '13'

      - name: Set up environment variables
        run: echo "DATABASE_URL=postgres://user:password@localhost:5432/your_database" >> $GITHUB_ENV

      - name: Prepare db
        run: bundle exec rake db:create

      - name: Test
        run: bundle exec rails test