name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install bundler
        run: |
          gem install bundler

      - name: Cache gems
        id: cache-gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle

      - name: Setup env
        run: cp config/application.example.yml config/application.yml

      - name: Prepare db
        run: bundle exec rake db:create

      - name: Test
        run: bundle exec rails test